{% set name = "qmsolve" %}
{% set version = "1.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/qmsolve-{{ version }}.tar.gz
  sha256: a4cb1c1b72b5282ed7b6724d288f9da025604c531e8fdd4cb15df712a40b1eb2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - h5py
    - matplotlib-base
    - mayavi
    - numpy
    - python >=3.7
    - scipy

test:
  imports:
    - qmsolve
    - qmsolve.particle_system
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/quantum-visualizations/qmsolve
  summary: A module for solving and visualizing the Schrödinger equation
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
