{% set name = "qmsolve" %}
{% set version = "1.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/qmsolve-{{ version }}.tar.gz
  sha256: 632f69af5ef2f3e5fc38c0f7a16cd3032c3a064de212078ba3e1ecc0799f966e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - h5py
    - matplotlib-base
    - mayavi
    - numpy
    - python >=3.7
    - scipy

test:
  imports:
    - qmsolve
    - qmsolve.particle_system
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/quantum-visualizations/qmsolve
  summary: A module for solving and visualizing the Schrödinger equation
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
