{% set name = "qmsolve" %}
{% set version = "2.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/qmsolve-{{ version }}.tar.gz
  sha256: 2dd60cd6b086f7b301141666666d3f3b99c66f76bb35b74cdd84b08ddd6a3423

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - h5py
    - matplotlib-base
    - mayavi
    - numpy
    - python >={{ python_min }}
    - progressbar >=2.5
    - scipy

test:
  imports:
    - qmsolve
    - qmsolve.particle_system
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/quantum-visualizations/qmsolve
  summary: A module for solving and visualizing the Schrödinger equation
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
